config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "categories#index"
  resources :users, only: [:edit, :update]
  resources :categories, only: [:index, :new, :create] do
    resources :messages, only: [:index, :new,:create]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_users
  has_many :users, through: :category_users
  has_many :messages
  validates :name, presence: true, uniqueness: true
end

app/models/category_message.rb
class CategoryMessage < ApplicationRecord

end

app/models/category_user.rb
class CategoryUser < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :category_users
  has_many :categories, through: :category_users
  has_many :category_messages
  has_many :messages

end

app/models/user_message.rb
class UserMessage < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  end
   
  def new
    @category = Category.new
    @category.users << current_user
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  private
  def category_params
    params.require(:category).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
  end

  def new
    @message = Message.new
    @messages = @category.messages.includes(:user)
  end

  def create
    @message = @category.messages.new(message_params)
    if @message.save
      redirect_to category_messages_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :memo).merge(user_id: current_user.id)
  end

  def set_group
    @category = Category.find(params[:category_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def updtae
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

    private

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/deadline_helper.rb
module DeadlineHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.haml
.wrapper4
  = render 'messages/top'
  = render 'messages/side'

app/views/categories/new.html.haml
= form_with model: @category, local: true do |f|
  = f.text_field :name, class: "SettingGroupForm__input", placeholder: "カテゴリー名を入力してください"
  = f.collection_check_boxes :user_ids, User.all, :id, :name
  = f.submit "カテゴリー作成", class: "SettingGroupForm__button"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todoapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_main.html.haml
.content
  .main
    .sub-title
      .main-title
        = @category.name


  .main-content
    .main-content__list
      .main-content__list__list-name
        = link_to new_category_message_path(current_user) do
          = icon('fas','plus')
        list
      .main-content__list__memo
        memo
    .main-content__review
      - current_user.messages.each do |message|
        .write-list
          = message.name
        .write-memo
          = message.memo

app/views/messages/_messages.html.haml
.main-content__review{data: {message: {id: message.id}}}
  //- current_user.messages.each do |message|
  .write-list
    = message.name
    //= message.name
  .write-memo
    =message.user.memo
        //= message.memo

app/views/messages/_side.html.haml
.side-bar
  .side-bar__main
    .first-list
      カテゴリー
      = link_to new_category_path(current_user) do
        = icon('fas','plus')
    .first-name__list-name
      - current_user.categories.each do |category|
        .group-block
          = link_to category_messages_path(category) do
            .group-name
              = category.name

app/views/messages/_top.html.haml
.header
  .header__title
    %p タスク管理
  .header__navi
    .header__navi__edit
      = link_to edit_user_path(current_user) do
        %p edit
        
    

app/views/messages/_under.html.haml
.under

app/views/messages/index.html.haml
.wrapper
  = render "top"
.wrapper
  = render "side"
  = render "main"
.wrapper3
  = render "under"

app/views/messages/new.html.haml
= form_with model: [@category, @message], url: category_messages_path, local: true do |f|
  = f.text_field :name, class: "SettingGroupForm__input", placeholder: "list名を入力してください"
  = f.text_area :memo, class: "SettingGroupForm__input", placeholder: "memoを入力してください"
  = f.submit "task登録", class: "SettingGroupForm__button"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'